"""
Django settings for MediasiteProvisioning project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mediasite',
    'canvas',
    'web',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'MediasiteProvisioning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'web/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MediasiteProvisioning.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ALLOWED_HOSTS = []

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(BASE_DIR, 'static'),
)

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'web/templates'),
)

###################################################################
#
#   Configuration values to be externalized in S3
#
###################################################################

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cdkbbnxtmcqcs*%0h(hj*0lla+(+&f-2+mao+ga6=c=10eut++'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Mediasite OAUTH defaults
OAUTH_CONSUMER_KEY='mediasite-email-address'
OAUTH_SHARED_SECRET='mediasite-email-address'

MEDIASITE_USERNAME = 'Nick_Carmello'
MEDIASITE_PASSWORD = 'daft-jaggy-beauty'

#############################################################
# Dev
#############################################################
MEDIASITE_API_KEY = '4746f072-7faa-4b91-8fdf-3b3aca910c26'
MEDIASITE_URL = 'https://dvsdev.mediasite.video.harvard.edu/mediasite/api/v1/{0}'
CANVAS_URL = 'https://canvas-sandbox.tlt.harvard.edu/api/v1/{0}'

#############################################################
# Test
#############################################################
# MEDIASITE_API_KEY = 'e368e3bb-4a6a-48a7-af17-a868300c6d63'
# MEDIASITE_URL = 'https://sandbox.mediasite.video.harvard.edu/mediasite/api/v1/{0}'
# CANVAS_URL = 'https://harvard.test.instructure.com/api/v1/{0}'

#############################################################
# Prod
#############################################################
# MEDIASITE_API_KEY = ''
# MEDIASITE_URL = ''
# CANVAS_URL = 'https://canvas.harvard.edu/api/v1/{0}'











CREATE_USER_PROFILES_FOR_TEACHERS = False

